name: noteflow
description: A task manager app with authentication and collaboration features.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2  # Keep only one version of the provider package
  flutter_quill: ^7.1.0
  flutter_local_notifications: ^14.0.0
  file_picker: ^9.2.2  # Only keep one version (removed duplicate)
  shared_preferences: ^2.5.2
  sqflite: ^2.3.0
  draggable_scrollbar: ^0.1.0
  flutter_calendar_carousel: ^2.3.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4  # Use a compatible version of flutter_secure_storage
  uuid: ^3.0.6
  table_calendar: ^3.0.8
  qr_flutter: ^4.1.0  # QR code generation
  mobile_scanner: ^3.2.0  # QR code scanning
  share_plus: ^10.1.4  # Ensure compatibility with other packages
  path_provider: ^2.0.12
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true






  




